### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by emcca029** [emcca029/githublab#1]
### StoryId:
A-0000
### Title:
As a team member, I want to test this GitHub repo so that I can assure that everything is working.
### Status (New, Implementing, Done ):
New

### AssignedTo:
All Team members
### Estimate:
1

### Acceptance Criteria:
All team members assign this issue to themselves. 
All team members let a comment on this issue. 
All team member push an empty commit where this issue is named. 

### Developer Notes:
[How to push empty commit?](https://coderwall.com/p/vkdekq/git-commit-allow-empty)
Just include #1 in your commit message to reference an issue without closing it.

**Comment by userpro215** [comment]
This is a test comment.
