### ISSUE TITLE
Setup Framework

### ISSUE THREAD

**Issue by userpro215** [emcca029/githublab#2]
StoryId:

A-0001

Title:

As a team member, I want to set up the project using the Framework so that the team is up to speed.

Status (New, Implementing, Done ):

Done

AssignedTo:

Earl 

Estimate:

2

Acceptance Criteria:

The application is working with the basic "Hello World"

Developer Notes:

**Comment by emcca029** [comment]
Please include links to the basic "Hello World" Application and Documentation.
